---
kind: pipeline
type: kubernetes
name: branch-terraform

platform:
  os: linux
  arch: amd64


trigger:
  event:
    exclude:
      - push
      - pull_request
      - tag
      - promote
      - rollback
# to reinstate uncomment the following 
# trigger:
#   event:
#     - push
  branch:
    - main

steps:
  - name: terraform apply
    image: hashicorp/terraform:latest
    environment:
      KEYCLOAK_URL:
        from_secret: KEYCLOAK_URL
      KEYCLOAK_REALM:
        from_secret: KEYCLOAK_REALM
      KEYCLOAK_CLIENT_ID:
        from_secret: KEYCLOAK_CLIENT_ID
      KEYCLOAK_CLIENT_SECRET:
        from_secret: KEYCLOAK_CLIENT_SECRET
      TF_VAR_callisto_realm:
        from_secret: TF_VAR_callisto_realm
      TF_VAR_callisto_url:
        from_secret: TF_VAR_callisto_url
      TF_VAR_include_test_users:
        from_secret: TF_VAR_include_test_users
      TF_S3_ACCESS_KEY:
        from_secret: TF_S3_ACCESS_KEY
      TF_S3_SECRET_KEY:
        from_secret: TF_S3_SECRET_KEY
    commands:
      - cd ./config
      - terraform init -reconfigure -backend-config="region=eu-west-2" -backend-config="access_key=$TF_S3_ACCESS_KEY" -backend-config="secret_key=$TF_S3_SECRET_KEY" -backend-config="bucket=ho-callisto-terraform" -backend-config="key=terraform/build/callisto-auth-keycloak/callisto-branch"
      - terraform plan -input=false -out=tfplan
      - terraform apply -input=false -auto-approve tfplan
