---
kind: pipeline
type: kubernetes
name: branch-terraform

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
#  branch:
#    - main

steps:
  - name: terraform apply
    image: hashicorp/terraform:latest
    environment:
      KEYCLOAK_URL:
        from_secret: KEYCLOAK_URL
      KEYCLOAK_CLIENT_ID:
        from_secret: KEYCLOAK_CLIENT_ID
      KEYCLOAK_USER:
        from_secret: KEYCLOAK_USER
      KEYCLOAK_PASSWORD:
        from_secret: KEYCLOAK_PASSWORD
      TF_VAR_callisto_realm:
        from_secret: TF_VAR_callisto_realm
      TF_VAR_callisto_url:
        from_secret: TF_VAR_callisto_url
      TF_VAR_include_test_users:
        from_secret: TF_VAR_include_test_users
      TF_S3_ACCESS_KEY:
        from_secret: TF_S3_ACCESS_KEY
      TF_S3_SECRET_KEY:
        from_secret: TF_S3_SECRET_KEY
    commands:
      - cd ./config
      - terraform init -reconfigure -backend-config="region=eu-west-2" -backend-config="access_key=$TF_S3_ACCESS_KEY" -backend-config="secret_key=$TF_S3_SECRET_KEY" -backend-config="bucket=ho-callisto-terraform" -backend-config="key=terraform/build/callisto-auth-keycloak/callisto-branch"
      - KEYCLOAK_URL=$KEYCLOAK_URL KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID KEYCLOAK_USER=$KEYCLOAK_USER KEYCLOAK_PASSWORD=$KEYCLOAK_PASSWORD TF_VAR_callisto_realm=$TF_VAR_callisto_realm TF_VAR_callisto_url=$TF_VAR_callisto_url TF_VAR_include_test_users=$TF_VAR_include_test_users terraform apply




#  - name: terraform apply
#    image: jmccann/drone-terraform:latest
#    settings:
#      actions:
#        - apply
#      plan: false
#      secrets:
#        KEYCLOAK_URL:
#          from_secret: KEYCLOAK_URL
#        KEYCLOAK_CLIENT_ID:
#          from_secret: KEYCLOAK_CLIENT_ID
#        KEYCLOAK_USER:
#          from_secret: KEYCLOAK_USER
#        KEYCLOAK_PASSWORD:
#          from_secret: KEYCLOAK_PASSWORD
#        TF_VAR_callisto_realm:
#          from_secret: TF_VAR_callisto_realm
#        TF_VAR_callisto_url:
#          from_secret: TF_VAR_callisto_url
#        TF_VAR_include_test_users:
#          from_secret: TF_VAR_include_test_users
