name: Docker
on:
  push:
    branches:
      - main
      - "**EAHW-**"
      - "**eahw-**"

jobs:
  build-multi-arch-image:
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: keycloak/keycloak-containers
          ref: "${{ inputs.keycloak_version }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          registry: quay.io/ukhomeofficedigital

      - name: Build and Push multi-arch image to Amazon ECR
        run: |
          cd server
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag quay.io/ukhomeofficedigital/callisto-keycloak:'${{ inputs.keycloak_version }}' .

  build-docker-image:
    needs: build-multi-arch-image
    defaults:
      run:
        working-directory: ./config
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-west-2
      KEYCLOAK_CLIENT_ID: admin-cli
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      TF_VAR_callisto_realm: callisto
      TF_VAR_callisto_url: https://web.callisto.localhost
      TF_VAR_include_test_users: true
      DOCKER_REGISTRY: quay.io/ukhomeofficedigital
      DOCKER_REPO: callisto-auth-keycloak

    services:
      localstack:
        image: localstack/localstack
        options: --name localstack
        ports:
          - 4566
        env:
          SERVICES: s3

    steps:
      - uses: actions/checkout@v2

      - name: Start Keycloak container
        run: docker run --name keycloak -p 9090:8080 -d --env KEYCLOAK_USER=admin --env KEYCLOAK_PASSWORD=admin ${DOCKER_REGISTRY}/callisto-keycloak:15.0.2

      - name: Wait for Keycloak
        run: (docker logs -f keycloak &) | grep -m 1 "Admin console listening on"
        timeout-minutes: 1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CALLISTO_KEYCLOAK_DEPLOY_BOT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CALLISTO_KEYCLOAK_DEPLOY_BOT_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Create S3 local bucket
        run: |
          aws s3api create-bucket --bucket terraform --endpoint-url http://localhost:${{ job.services.localstack.ports[4566] }} --create-bucket-configuration LocationConstraint=eu-west-2

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure -backend-config="endpoint=http://localhost:${{ job.services.localstack.ports[4566] }}" -backend-config="region=eu-west-2" -backend-config="skip_credentials_validation=true" -backend-config="skip_metadata_api_check=true" -backend-config="bucket=terraform" -backend-config="key=terraform.tfstate" -backend-config="force_path_style=true"

      - name: Terraform Plan
        id: plan
        env:
          KEYCLOAK_URL: http://localhost:9090
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        id: apply
        env:
          KEYCLOAK_URL: http://localhost:9090
        run: terraform apply -input=false -auto-approve -input=false tfplan

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.QUAY_ROBOT_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Docker Stop and Commit
        run: |
          docker stop keycloak
          docker commit keycloak ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:${{ github.sha }}-amd
        shell: bash

      - name: Build ARM image
        uses: docker/build-push-action@v3
        with:
          registry: quay.io
          platforms: linux/arm64
          context: .
          push: false
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:${{ github.sha }}-arm
          build-args: |
            image=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}:${{ github.sha }}-amd

      - name: Push multi-arch images and manifest to QUAY Registry
        run: |
          if [ "$GITHUB_REF_NAME" = "main" ]
          then
            TAG=latest
          elif [[ $GITHUB_REF_NAME =~ (EAHW-[0-9]*|eahw-[0-9]*) ]]
          then
            TAG=${match/#E/E}${BASH_REMATCH/#E/E}
          else
            TAG=${GITHUB_SHA}
          fi
          docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GITHUB_SHA}-amd ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GITHUB_SHA}-amd
          docker tag ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GITHUB_SHA}-arm ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GITHUB_SHA}-arm
          docker image push --all-tags ${DOCKER_REGISTRY}/${DOCKER_REPO}
          docker manifest create ${DOCKER_REGISTRY}/${DOCKER_REPO}:${TAG} --amend ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GITHUB_SHA}-amd --amend ${DOCKER_REGISTRY}/${DOCKER_REPO}:${GITHUB_SHA}-arm
          docker manifest push ${DOCKER_REGISTRY}/${DOCKER_REPO}:${TAG}
