name: Docker
on:
  push:
    branches_ignore:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    services:
      keycloak:
        image: quay.io/keycloak/keycloak:15.0.2
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        ports:
        - 8080:tcp

    steps:
    - uses: actions/checkout@v1
    - name: Wait for Keycloak
      run: ./wait_for_keycloak.sh keycloak
