name: Docker
on:
  push:
    branches_ignore:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    services:
      keycloak:
        image: quay.io/keycloak/keycloak:15.0.2
        options: --name keycloak
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        ports:
        - 8080
      localstack:
        image: localstack/localstack
        options: --name localstack
        ports:
        - 4566
        env:
          SERVICES: s3

    steps:
    - uses: actions/checkout@v1
    - name: Wait for Keycloak
      run: (docker logs -f keycloak &) | grep -m 1 "Admin console listening on"
      timeout-minutes: 1
    # - name: Wait for localstack
    #   run: (docker logs -f localstack &) | grep -m 1 "^Ready."
    #   timeout-minutes: 2