name: Docker
on:
  push:
    branches_ignore:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    services:
      keycloak:
        image: quay.io/keycloak/keycloak:15.0.2
        options: --name keycloak
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
        ports:
        - 8080

    steps:
    - uses: actions/checkout@v1
    - name: Wait for Keycloak
      shell: 'script -q -e -c "bash {0}"'
      run: docker logs -f keycloak | grep -m 1 "Admin console listening on"
      timeout-minutes: 1