name: Keycloak AMD and ARM
on:
  workflow_dispatch:
  push:
    branches:
      - 'EAHW-2540/task/create-multi-arch-keycloack-image'

jobs:
  build-multi-arch-image:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: keycloak/keycloak-containers
          ref: '15.0.2'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build multi-arch image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          platforms: linux/amd64,linux/arm64
          push: false
          tags: callisto/keycloak:15.0.2
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CALLISTO_AUTH_KEYCLOAK_DEPLOY_BOT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CALLISTO_AUTH_KEYCLOAK_DEPLOY_BOT_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      -
        name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      -
        name: Push multi-arch image to ECR Registry
        run: docker image push --all-tags 340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/keycloak:15.0.2
