name: Keycloak AMD and ARM
on:
  workflow_dispatch:
    inputs:
      keycloak_version:
        description: 'Keycloak version'
        required: true
        default: '15.0.2'
  push:
    inputs:
      keycloak_version:
        description: 'Keycloak version'
        required: true
        default: '15.0.2'
    branches:
      - 'EAHW-2540/task/create-multi-arch-keycloack-image'

jobs:
  build-multi-arch-image:
    runs-on: ubuntu-latest

    steps:
      -
        name: Output Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          repository: keycloak/keycloak-containers
          ref: '${{ inputs.keycloak_version }}'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CALLISTO_KEYCLOAK_DEPLOY_BOT_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CALLISTO_KEYCLOAK_DEPLOY_BOT_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      -
        name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      -
        name: Build and Push multi-arch image to ECR Registry
        run: |
          cd server
          docker buildx build --push --platform linux/amd64,linux/arm64 --tag 340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/keycloak:'${{ inputs.keycloak_version }}' .
          docker image ls
