name: Validate Configuration
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    strategy:
      matrix:
        stage: ["development", "test", "production"]
    # set the environment to use (environment must exist and be named the same as the stage here)
    environment:
      name: ${{ matrix.stage }}
    defaults:
      run:
        working-directory: ./config
    runs-on: ubuntu-latest
    env:
      KEYCLOAK_CLIENT_ID: ${{ secrets.tf_kc_client_id }}
      KEYCLOAK_CLIENT_SECRET: ${{ secrets.tf_kc_client_secret }}
      KEYCLOAK_REALM: ${{ secrets.tf_kc_realm }}
      KEYCLOAK_URL: ${{ secrets.tf_kc_url }}
      TF_VAR_callisto_realm: ${{ secrets.tf_kc_realm }}
      TF_VAR_callisto_url: ${{ secrets.tf_callisto_url }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        # To reinstate changes uncomment the following
        #run: terraform init -reconfigure -backend-config="region=${{ secrets.tf_be_region }}" -backend-config="access_key=${{ secrets.tf_be_access_key }}" -backend-config="secret_key=${{ secrets.tf_be_secret_key }}" -backend-config="bucket=${{ secrets.tf_be_bucket }}" -backend-config="key=${{ secrets.tf_be_bucket_key }}"
        # To reinstate changes, remove line below
        run: terraform init -backend=false # As the S3 buckets are decommissioned, backend is set to false.

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive -diff

    # To reinstate changes uncomment the following
    # - name: Terraform Plan
    #   if: github.event_name == 'pull_request'
    #   id: plan
    #   run: terraform plan
